In [2]:
import numpy as np
import pandas as pd
import re

In [3]:
df=pd.read_csv('/content/astronauts.csv')
display(df)

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           

In [4]:
print(df.loc[0][1])

2004.0


In [6]:
df.size

6783

In [7]:
df.values

array([['Joseph M. Acaba', 2004.0, 19.0, ...,
        'STS-119 (Discovery), ISS-31/32 (Soyuz)', nan, nan],
       ['Loren W. Acton', nan, nan, ..., 'STS 51-F (Challenger)', nan,
        nan],
       ['James C. Adamson', 1984.0, 10.0, ...,
        'STS-28 (Columbia), STS-43 (Atlantis)', nan, nan],
       ...,
       ['Alfred M. Worden', 1966.0, 5.0, ..., 'Apollo 15', nan, nan],
       ['John W. Young', 1962.0, 2.0, ...,
        'Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS-1 (Columbia), STS-9 (Columbia)',
        nan, nan],
       ['George D. Zamka', 1998.0, 17.0, ...,
        'STS-120 (Discovery), STS-130 (Endeavor)', nan, nan]],
      dtype=object)

In [8]:
type(df.values)

numpy.ndarray

In [9]:
df.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired  5/20/1951  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired  1/20/1930  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                              STS 51-F (Challenger)        NaN           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaN           NaN  
4                               Gemini 12, Apollo 11        NaN           NaN

In [10]:
df.tail()

Name    Year  Group   Status Birth Date  \
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [11]:
col01 = np.random.randint(10,size = 5)
col02 = np.random.randint(10,size = 5)
col03 = np.random.randint(10,size = 5)

In [12]:
dictionary = {"ones" : col01,'two': col02,'three' : col03}
print(dictionary)

{'ones': array([4, 1, 7, 1, 4]), 'two': array([1, 7, 2, 1, 7]), 'three': array([7, 0, 6, 9, 4])}


In [13]:
display(dictionary)

{'ones': array([4, 1, 7, 1, 4]),
 'two': array([1, 7, 2, 1, 7]),
 'three': array([7, 0, 6, 9, 4])}

In [14]:
df02 =pd.DataFrame(dictionary)
display(df02)

ones  two  three
0     4    1      7
1     1    7      0
2     7    2      6
3     1    1      9
4     4    7      4

In [15]:
df02[0:1]

ones  two  three
0     4    1      7

In [16]:
df02.drop(2,axis = 0,inplace = True)
display(df)

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           

In [17]:
df02.index

Int64Index([0, 1, 3, 4], dtype='int64')

In [18]:
df[0:3]

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   

                                          Alma Mater  Undergraduate Major  \
0  University of California-Santa Barbara; Univer...              Geology   
1   Montana State University; University of Colorado  Engineering Physics   
2          US Military Academy; Princeton University          Engineering   

          Graduate Major Military Rank    Military Branch  Space Flights  \
0                Geology           NaN                NaN              2   
1          Solar Physics           NaN                NaN              1   
2  Aerospace Engineering       Colonel  US Army (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   

                                 Missions Death Date Death Mission  
0  STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                   STS 51-F (Challenger)        NaN           NaN  
2    STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN

In [19]:
k=['Year','Group']

In [20]:
df.drop(k,axis=1)

Name   Status Birth Date        Birth Place Gender  \
0          Joseph M. Acaba   Active  5/17/1967      Inglewood, CA   Male   
1           Loren W. Acton  Retired   3/7/1936       Lewiston, MT   Male   
2         James C. Adamson  Retired   3/3/1946         Warsaw, NY   Male   
3          Thomas D. Akers  Retired  5/20/1951      St. Louis, MO   Male   
4              Buzz Aldrin  Retired  1/20/1930      Montclair, NJ   Male   
..                     ...      ...        ...                ...    ...   
352          David A. Wolf  Retired  8/23/1956   Indianapolis, IN   Male   
353  Neil W. Woodward III   Retired  7/26/1962        Chicago, IL   Male   
354       Alfred M. Worden  Retired   2/7/1932        Jackson, MI   Male   
355          John W. Young  Retired  9/24/1930  San Francisco, CA   Male   
356        George D. Zamka  Retired  6/29/1962    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \


In [21]:
df['yeni']=df['Space Walks (hr)']*df['Space Walks']

In [22]:
df

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           

In [23]:
num1=np.random.randint(1,30,size = (10,3))
print(num1)

[[24  5 14]
 [ 9 17 21]
 [16 12 10]
 [ 4  4 11]
 [25 29  3]
 [21 12 10]
 [16  5 18]
 [ 9 16 27]
 [17 13  2]
 [15 12 20]]


In [24]:
df03 = pd.DataFrame(num1,columns = ['stun01','stun02','stun03'])
display(df03)

stun01  stun02  stun03
0      24       5      14
1       9      17      21
2      16      12      10
3       4       4      11
4      25      29       3
5      21      12      10
6      16       5      18
7       9      16      27
8      17      13       2
9      15      12      20

In [25]:
df03.loc[0:3]

stun01  stun02  stun03
0      24       5      14
1       9      17      21
2      16      12      10
3       4       4      11